# Generated by Django 2.2.7 on 2020-07-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200718_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('W', 'WORK'), ('H', 'HOME')], max_length=2),
        ),
    ]
